additional_info: "부적절 발언 탐지 과제 v2"
seed: 7412013 # 42 # 115 # 2025 # 7412013
deterministic: false
hf_token: ""
use_lora: true
use_qlora: false
data_raw_dir: "data/other_for_conf_for_cot_perspectives"
prompt_version: "soft_cot" # soft_cot # original
data_question_length_limit: -1 # 800 # -1 means no limit
data_shuffle: false
data_hangul_info: false

# dpo 관련
# 기존의 sft 모델 경로
sft_model_for_dpo: ""


# only test
save_dir: "" # it will be set by the function
adapter_dir: "lora_adapter"
test_result_dir: "test_results"

only_decode: true
is_cot: true
perspective_count: 1
dt_sp_number: true
use_cache: true
